### ISSUE TITLE
hendlers

### ISSUE THREAD

**Issue by asakl** [asakl/Trivia-Project#2]
1. each new request from client create new hendler,
so if i have one user that create room,  the second user dosnt see the room...
so, it's need to be some shared resource or sonething...

**Comment by IshaySela** [comment]
Done. Now, the RoomManager and LoginManager are shared resource via pointers.
In addition, a player cannot log in twice or more at the same time.

**Comment by asakl** [comment]
when i ask for all users in room i get null.
pls fix

**Comment by IshaySela** [comment]
The issue is fixed.
