### ISSUE TITLE
client JSON deserialization issue 

### ISSUE THREAD

**Issue by IshaySela** [asakl/Trivia-Project#3]
The client throw an exception when trying to deserialize the string from the server. The string is getRooms request, and is JSON of JSON's. The string is similar to this:

{ "status" : "status", "rooms" : { "1" : room1,"2":room2 }  }

**Comment by asakl** [comment]
WTH? you sending some huge shit... like lots of sub-jsons and lots of '\'
pls fix the convert func...

**Comment by asakl** [comment]
OK i think it's fix.
for sure for one room

**Comment by IshaySela** [comment]
Great! But please next write more informative commit message, not just "fixed the issue".
