### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by asakl** [asakl/Trivia-Project#4]
Please fix all those issues:
1) Fix that every user will not be "unknown" user                                                       -V
2) Fix that will not be two rooms with same name                                                     - V
3) Handle "close room" or stuff                                                                                  -  V
4) Handle "get highscores" and "get user info"                                                          -
5) Please send full room data in "get rooms" (num of players, num of question etc)     -  V
7) Admin request handler in the communicator -  V

**Comment by IshaySela** [comment]
Close room request id: 13
Start game request: 14
