### ISSUE TITLE
Client players in room issue

### ISSUE THREAD

**Issue by IshaySela** [asakl/Trivia-Project#8]
The client does not remove a player who left the room from the players list.
Asa, please fix.

**Comment by asakl** [comment]
1.  U dont handle code 16 (leave room).
2.  U dont handle close room good... if i close room and then reopen i have excption when i press with other user join room...
pls fix

**Comment by IshaySela** [comment]
1) Im handling code 16.
2 is because json["rooms"] is empty.

**Comment by IshaySela** [comment]
For now, the issue is fixed, But the solution is'nt great - its basically ignoring the problem.
Don't close the issue otherwise I will forget this bug.
Lets move on the version 4.0.0.
